### ISSUE TITLE
F# 

### ISSUE THREAD

**Issue by keithn** [devfreebooks/devfreebooks.github.io#16]
https://www.gitbook.com/book/swlaschin/fsharpforfunandprofit/details

can't be bothered going through your pull request process to just add a book ( super ridiculous way of doing things).

**Comment by caio-ribeiro-pereira** [comment]
No problems, I will add a google form soon and thank you for this link!

**Comment by caio-ribeiro-pereira** [comment]
@keithn please submit this book by this form: https://docs.google.com/forms/d/1V74zbYW8b1x1d7kIj_bnMpgMUVybM53pusrtCJlTI4Y/prefill

thanks!

**Comment by caio-ribeiro-pereira** [comment]
@keithn  Sorry I sent the wrong link, this is the correct one: https://docs.google.com/forms/d/e/1FAIpQLSeXsmlLo3S7lJF82LGTOMoMpA4vg_T38Ez47gQoU6P6KaFwQg/viewform
