### ISSUE TITLE
TFE... Not sure about it[C Ebooks/PDFs]

### ISSUE THREAD

**Issue by Darksider3** [devfreebooks/devfreebooks.github.io#3]
Don't even know what the heck "TFE Times" is(maybe it's a candidate for DMCA Takedown, but dont know), but there are several PDFs/Books too: https://tfetimes.com/free-c-books/

It doesn't look like a pirating website.

**Comment by caio-ribeiro-pereira** [comment]
A lot of these books is piracy pdf, so it won't be accepted here

**Comment by Darksider3** [comment]
Okay, thats something i expected. How about https://github.com/fffaraz/awesome-cpp/blob/master/books.md? :)

**Comment by caio-ribeiro-pereira** [comment]
@Darksider3 all books from awesome-cpp are accepted, feel free to add them!

**Comment by Darksider3** [comment]
;3 i will. Thanks for patience.
