### ISSUE TITLE
Architecture / Design Patterns platform

### ISSUE THREAD

**Issue by alexpana** [devfreebooks/devfreebooks.github.io#7]
Game Programming Patterns is a pretty nice book (free online version): http://gameprogrammingpatterns.com/ but there isn't any platform for it. Perhaps something like "Design Patterns" would be appropriate.

**Comment by caio-ribeiro-pereira** [comment]
Which language is used in this book?

**Comment by alexpana** [comment]
C++

**Comment by lennonjesus** [comment]
How about "Game Programming" or "Games"?

**Comment by caio-ribeiro-pereira** [comment]
If is a book which uses C++ language, just add the book into C++ category :)

**Comment by alexpana** [comment]
It's not really about C++ or about Games. Those are just used as a support scaffolding. The book's main focus is design patterns applicable in any language or domain, with examples from gamedev.

This is why I believe books shouldn't be categorized by language. While some books like: "Closure for the Brave And True" or "Why's (Poignant) Guide to Ruby" or "Learn You a Haskell for Great Good!" are dedicated to teaching a programming language, other books cover other topics. Would you add an algorithms book to the "C" category because it has examples in the C language?

A better approach would be to use tags in order to place a book in multiple categories. This way You can show the tags as categories on the front page, but you could find the same book in multiple categories.

**Comment by caio-ribeiro-pereira** [comment]
Well you're right, so I will add soon the category Design Patterns, and feel free to submit your book via PR or via Google Forms https://docs.google.com/forms/d/e/1FAIpQLSeXsmlLo3S7lJF82LGTOMoMpA4vg_T38Ez47gQoU6P6KaFwQg/viewform
Thanks!
